name: subby
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dynamic_color: ^1.5.4
  http: ^0.13.5
  xml2json: ^5.3.5
  logging: ^1.1.0
  just_audio: ^0.9.30
  just_audio_windows: ^0.2.0
  just_audio_background: ^0.0.1-beta.8
  rxdart: ^0.27.7
  audio_session: ^0.1.11
  modal_bottom_sheet: ^2.1.2
  sheet: ^0.0.4+1
  audio_video_progress_bar: ^0.11.0
  provider: ^6.0.4
  get: ^4.6.5
  shared_preferences: ^2.0.15
  settings_ui: ^2.0.2
  connectivity_plus: ^3.0.2
  flutter_slidable: ^2.0.0
  audio_service: ^0.18.8
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/monochrome.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
